# 1. Info

EDA for the __*premier_league.csv*__ file inside the __*data/enriched_data/*__ folder.

# 2. EDA

## 2.1 Import Libraries

In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 2.2. Read the data

In [8]:
data = pd.read_csv("../data/enriched_data/premier_league.csv")

## 2.3. Quick peek to the data

In [9]:
data.head().T

,0,1,2,3,4
Date,2000-08-19,2000-08-19,2000-08-19,2000-08-19,2000-08-19
Team,6,21,16,30,41
Opponent,21,6,30,16,24
FTG_scored,4,0,4,2,1
FTG_received,0,4,2,4,3
FT_Result,1,0,1,0,0
HTG_scored,2,0,1,0,1
HTG_received,0,2,0,1,1
HT_Result,1,0,1,0,2
season,2000-2001,2000-2001,2000-2001,2000-2001,2000-2001
shots,17,8,17,12,6
shots_received,8,17,12,17,16
shots_target,14,4,10,5,3
shots_target_received,4,14,5,10,9
fouls_commited,13,12,19,14,15
fouls_received,12,13,14,19,21
corners,6,6,7,7,8
corners_against,6,6,7,7,4
yellow_cards,1,2,1,2,5
yellow_cards_opponent,2,1,2,1,3
red_cards,0,0,0,0,1
red_cards_opponent,0,0,0,0,0
Home,1,0,1,0,1
FTG_scored_Total,0,0,0,0,0
FTG_received_Total,0,0,0,0,0
HTG_scored_Total,0,0,0,0,0
HTG_received_Total,0,0,0,0,0
shots_Total,0,0,0,0,0
shots_received_Total,0,0,0,0,0
shots_target_Total,0,0,0,0,0
shots_target_received_Total,0,0,0,0,0
fouls_commited_Total,0,0,0,0,0
fouls_received_Total,0,0,0,0,0
corners_Total,0,0,0,0,0
corners_against_Total,0,0,0,0,0
yellow_cards_Total,0,0,0,0,0
yellow_cards_opponent_Total,0,0,0,0,0
red_cards_Total,0,0,0,0,0
red_cards_opponent_Total,0,0,0,0,0
points,0,0,0,0,0
goal_difference,0,0,0,0,0
position,1,2,3,4,5
Win,1,0,1,0,0
win_rate,0.0,0.0,0.0,0.0,0.0
mooving_win_rate,0.0,0.0,0.0,0.0,0.0
mooving_goals_scored,0.0,0.0,0.0,0.0,0.0
mooving_goals_received,0.0,0.0,0.0,0.0,0.0

In [10]:
data.tail().T

,17573,17574,17575,17576,17577
Date,2023-09-17,2023-09-17,2023-09-17,2023-09-18,2023-09-18
Team,16,15,9,14,45
Opponent,31,9,15,45,14
FTG_scored,0,0,1,1,1
FTG_received,0,1,0,1,1
FT_Result,2,0,1,2,2
HTG_scored,0,0,0,0,1
HTG_received,0,0,0,1,0
HT_Result,2,2,2,0,1
season,2023-2024,2023-2024,2023-2024,2023-2024,2023-2024
shots,14,8,13,14,10
shots_received,13,13,8,10,14
shots_target,6,1,4,4,3
shots_target_received,4,4,1,3,4
fouls_commited,20,12,10,16,10
fouls_received,15,10,12,10,16
corners,7,1,11,5,4
corners_against,1,11,1,4,5
yellow_cards,5,1,1,2,3
yellow_cards_opponent,1,1,1,3,2
red_cards,0,0,0,0,1
red_cards_opponent,0,0,0,1,0
Home,0,1,0,1,0
FTG_scored_Total,5,2,8,6,3
FTG_received_Total,5,2,4,6,8
HTG_scored_Total,3,1,3,3,1
HTG_received_Total,2,2,2,3,4
shots_Total,67,16,65,38,25
shots_received_Total,43,13,38,61,36
shots_target_Total,18,6,26,13,6
shots_target_received_Total,11,8,9,21,16
fouls_commited_Total,39,13,36,37,27
fouls_received_Total,45,11,38,44,20
corners_Total,27,6,36,12,11
corners_against_Total,11,4,10,34,10
yellow_cards_Total,11,2,5,12,6
yellow_cards_opponent_Total,12,1,10,12,3
red_cards_Total,0,0,1,1,0
red_cards_opponent_Total,1,0,1,0,0
points,4,1,10,6,0
goal_difference,0,0,4,0,-5
position,11,17,5,9,19
Win,0,0,1,0,0
win_rate,0.25,0.0,0.75,0.5,0.0
mooving_win_rate,0.2,0.0,0.8,0.4,0.0
mooving_goals_scored,2.6,0.4,3.6,3.0,0.8
mooving_goals_received,2.8,0.4,1.8,3.4,2.2

just by taking a look at the head and tail of the Data Frame a difference in values can be noticed, the first rows of the data contains a lot of zeros.

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17578 entries, 0 to 17577
Data columns (total 47 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         17578 non-null  object
 1   Team                         17578 non-null  int64
 2   Opponent                     17578 non-null  int64
 3   FTG_scored                   17578 non-null  int64
 4   FTG_received                 17578 non-null  int64
 5   FT_Result                    17578 non-null  int64
 6   HTG_scored                   17578 non-null  int64
 7   HTG_received                 17578 non-null  int64
 8   HT_Result                    17578 non-null  int64
 9   season                       17578 non-null  object
 10  shots                        17578 non-null  int64
 11  shots_received               17578 non-null  int64
 12  shots_target                 17578 non-null  int64
 13  shots_target_received        17578 non-null  int64
 14  fouls_commited               17578 non-null  int64
 15  fouls_received               17578 non-null  int64
 16  corners                      17578 non-null  int64
 17  corners_against              17578 non-null  int64
 18  yellow_cards                 17578 non-null  int64
 19  yellow_cards_opponent        17578 non-null  int64
 20  red_cards                    17578 non-null  int64
 21  red_cards_opponent           17578 non-null  int64
 22  Home                         17578 non-null  int64
 23  FTG_scored_Total             17578 non-null  int64
 24  FTG_received_Total           17578 non-null  int64
 25  HTG_scored_Total             17578 non-null  int64
 26  HTG_received_Total           17578 non-null  int64
 27  shots_Total                  17578 non-null  int64
 28  shots_received_Total         17578 non-null  int64
 29  shots_target_Total           17578 non-null  int64
 30  shots_target_received_Total  17578 non-null  int64
 31  fouls_commited_Total         17578 non-null  int64
 32  fouls_received_Total         17578 non-null  int64
 33  corners_Total                17578 non-null  int64
 34  corners_against_Total        17578 non-null  int64
 35  yellow_cards_Total           17578 non-null  int64
 36  yellow_cards_opponent_Total  17578 non-null  int64
 37  red_cards_Total              17578 non-null  int64
 38  red_cards_opponent_Total     17578 non-null  int64
 39  points                       17578 non-null  int64
 40  goal_difference              17578 non-null  int64
 41  position                     17578 non-null  int64
 42  Win                          17578 non-null  int64
 43  win_rate                     17578 non-null  float64
 44  mooving_win_rate             17578 non-null  float64
 45  mooving_goals_scored         17578 non-null  float64
 46  mooving_goals_received       17578 non-null  float64
dtypes: float64(4), int64(41), object(2)
memory usage: 6.3+ MB

In [17]:
null_values = data.isnull().sum().reset_index()
null_values.columns = ['column','no_nulls']
null_values.query("no_nulls > 0")

Empty DataFrame
Columns: [column, no_nulls]
Index: []

The columns do not have null values.

In [13]:
data.describe()

,Team,Opponent,FTG_scored,FTG_received,FT_Result,HTG_scored,HTG_received,HT_Result,shots,shots_received,...,red_cards_Total,red_cards_opponent_Total,points,goal_difference,position,Win,win_rate,mooving_win_rate,mooving_goals_scored,mooving_goals_received
count,17578.000000,17578.000000,17578.000000,17578.000000,17578.000000,17578.000000,17578.000000,17578.000000,17578.000000,17578.000000,...,17578.000000,17578.000000,17578.000000,17578.000000,17578.000000,17578.000000,17578.000000,17578.000000,17578.000000,17578.000000
mean,20.501934,20.501934,1.343441,1.343441,0.872227,0.597565,0.597565,1.116452,12.116851,12.116851,...,1.382410,1.411765,25.174366,0.679201,10.287462,0.375924,0.361914,0.352975,22.091319,21.451451
std,12.576485,12.576485,1.241588,1.241588,0.779605,0.786802,0.786802,0.831843,5.161377,5.161377,...,1.435167,1.542253,18.184653,14.843884,5.806804,0.484374,0.212887,0.248224,16.874113,15.948177
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,-65.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,11.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,8.000000,...,0.000000,0.000000,11.000000,-7.000000,5.000000,0.000000,0.225806,0.200000,8.000000,7.800000
50%,20.000000,20.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,12.000000,12.000000,...,1.000000,1.000000,23.000000,0.000000,10.000000,0.000000,0.333333,0.400000,20.000000,19.800000
75%,30.000000,30.000000,2.000000,2.000000,1.000000,1.000000,1.000000,2.000000,15.000000,15.000000,...,2.000000,2.000000,37.000000,6.000000,15.000000,1.000000,0.500000,0.600000,32.800000,33.000000
max,45.000000,45.000000,9.000000,9.000000,2.000000,5.000000,5.000000,2.000000,43.000000,43.000000,...,7.000000,13.000000,97.000000,78.000000,20.000000,1.000000,1.000000,1.000000,100.000000,77.400000

There are 45 teams inside the data.

The maximun amount of goals scored is 9.

The maximun goals scored during the first half is 5.

The average amount of goals is 1.3, so we should be expecting goals in most of the matches.

In [18]:
data.query("mooving_goals_scored == 100")

,Date,Team,Opponent,FTG_scored,FTG_received,FT_Result,HTG_scored,HTG_received,HT_Result,season,...,red_cards_Total,red_cards_opponent_Total,points,goal_difference,position,Win,win_rate,mooving_win_rate,mooving_goals_scored,mooving_goals_received
13673,2018-05-13,21,23,1,0,1,0,0,2,2017-2018,...,2,3,97,78,1,1,0.837838,0.8,100.0,25.8

In [22]:
data.query("Team == 21").query("season == '2017-2018'")[["FTG_scored","mooving_goals_scored"]]["FTG_scored"].sum()

106