# 1. Info

This notebooks contains the feature importance analysis.

Before runing this notebook you should have run the "__data_preparation.ipynb__" notebook.

# 2. Feature importance analysis.

## 2.1. Import Libraries

In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mutual_info_score
from IPython.display import display

## 2.2. Read the data

In [4]:
data = pd.read_csv('../data/enriched_data/premier_league.csv')

In [5]:
data.columns = data.columns.str.lower().str.replace(' ', '_')

## 2.3. Setting up the validation framework

In [6]:
categorical_variables = ['team','opponent','season','home']
numerical_variables = ['ftg_scored_total','ftg_received_total','htg_scored_total','htg_received_total','shots_total','shots_received_total','shots_target_total','shots_target_received_total','fouls_commited_total','fouls_received_total','corners_total','corners_against_total','yellow_cards_total','yellow_cards_opponent_total','red_cards_total','red_cards_opponent_total','points','goal_difference','position','win_rate','mooving_win_rate','mooving_goals_scored','mooving_goals_received']
# target_variable = ['ftg_scored','ftg_received','ft_result','win']

In [8]:
df = data[categorical_variables + numerical_variables + ['win']].copy()

In [10]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

print(len(df_train))
print(len(df_test))
print(len(df_val))

df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train.win.values
y_val = df_val.win.values
y_test = df_test.win.values

del df_train['win']
del df_val['win']
del df_test['win']

10546
3516
3516

## 2.4 difference and risk ratio

In [17]:
global_win = df_full_train.win.mean()

In [21]:
for cat in categorical_variables:
    print(cat)
    df_group = df_full_train.groupby(cat).win.agg(['mean', 'count'])
    df_group['diff'] = df_group['mean'] - global_win
    df_group['risk_ratio'] = df_group['mean'] / global_win
    display(df_group)
    print()
    print()

team

          mean  count      diff  risk_ratio
team
0     0.218310    426 -0.158024    0.580097
1     0.618705    695  0.242372    1.644034
2     0.295316    491 -0.081018    0.784718
3     0.376812     69  0.000478    1.001271
4     0.206573    213 -0.169761    0.548909
5     0.216667     60 -0.159667    0.575731
6     0.321951    205 -0.054382    0.855495
7     0.348416    221 -0.027917    0.925818
8     0.291262    206 -0.085071    0.773947
9     0.568214    711  0.191880    1.509868
10    0.093750     32 -0.282583    0.249114
11    0.318452    336 -0.057881    0.846198
12    0.356601    659 -0.019732    0.947567
13    0.248996    249 -0.127337    0.661637
14    0.272727     33 -0.103606    0.724696
15    0.359534    687 -0.016799    0.955361
16    0.575630    714  0.199297    1.529575
17    0.291545    343 -0.084788    0.774699
18    0.260000    100 -0.116333    0.690877
19    0.328267    329 -0.048066    0.872278
20    0.351955    358 -0.024378    0.935222
21    0.546667    675  0.170333    1.452613
22    0.324176    182 -0.052158    0.861406
23    0.294845    485 -0.081488    0.783469
24    0.290970    299 -0.085363    0.773171
25    0.559371    699  0.183037    1.486370
26    0.277778     36 -0.098556    0.738116
27    0.166667     60 -0.209667    0.442870
28    0.332253    617 -0.044081    0.882868
29    0.384615     65  0.008282    1.022007
30    0.337079    623 -0.039255    0.895692
31    0.303371    178 -0.072963    0.806122
32    0.228070    399 -0.148263    0.606032
33    0.274510    204 -0.101824    0.729433
34    0.184783     92 -0.191551    0.491008
35    0.283582    268 -0.092751    0.753540
36    0.265116    215 -0.111217    0.704472
37    0.241758     91 -0.134575    0.642404
38    0.000000      4 -0.376333    0.000000
39    0.193548     93 -0.182785    0.514300
40    0.480797    703  0.104463    1.277582
41    0.200000     30 -0.176333    0.531444
42    0.306977    215 -0.069357    0.815704
43    0.295302    298 -0.081031    0.784682
44    0.226027    146 -0.150306    0.600604
45    0.278226    248 -0.098108    0.739307

opponent

              mean  count      diff  risk_ratio
opponent
0         0.472093    430  0.095760    1.254454
1         0.184922    703 -0.191412    0.491378
2         0.455466    494  0.079132    1.210272
3         0.418182     55  0.041848    1.111200
4         0.544601    213  0.168268    1.447124
5         0.587302     63  0.210968    1.560589
6         0.401961    204  0.025627    1.068098
7         0.433790    219  0.057457    1.152675
8         0.447115    208  0.070782    1.188083
9         0.202817    710 -0.173516    0.538929
10        0.677419     31  0.301086    1.800051
11        0.445428    339  0.069094    1.183599
12        0.383758    628  0.007425    1.019729
13        0.457983    238  0.081650    1.216961
14        0.441176     34  0.064843    1.172302
15        0.358974    702 -0.017359    0.953873
16        0.199715    701 -0.176619    0.530686
17        0.451807    332  0.075474    1.200551
18        0.511111     90  0.134778    1.358134
19        0.406528    337  0.030195    1.080234
20        0.394444    360  0.018111    1.048125
21        0.265487    678 -0.110847    0.705456
22        0.387978    183  0.011645    1.030943
23        0.422594    478  0.046261    1.122925
24        0.398671    301  0.022338    1.059356
25        0.204167    720 -0.172167    0.542515
26        0.451613     31  0.075280    1.200034
27        0.644068     59  0.267734    1.711429
28        0.405629    604  0.029296    1.077845
29        0.353846     65 -0.022487    0.940247
30        0.427663    629  0.051330    1.136394
31        0.481081    185  0.104748    1.278338
32        0.478589    397  0.102256    1.271717
33        0.509174    218  0.132841    1.352987
34        0.565217     92  0.188884    1.501906
35        0.459075    281  0.082741    1.219862
36        0.438356    219  0.062023    1.164808
37        0.527473     91  0.151139    1.401610
38        1.000000      3  0.623667    2.657218
39        0.606061     99  0.229727    1.610435
40        0.299712    694 -0.076622    0.796400
41        0.592593     27  0.216259    1.574648
42        0.477064    218  0.100731    1.267664
43        0.409396    298  0.033063    1.087855
44        0.509434    159  0.133101    1.353677
45        0.504132    242  0.127799    1.339589

season

               mean  count      diff  risk_ratio
season
2000-2001  0.364238    604 -0.012095    0.967861
2001-2002  0.373183    619 -0.003151    0.991628
2002-2003  0.382496    617  0.006163    1.016375
2003-2004  0.358333    600 -0.018000    0.952170
2004-2005  0.355738    610 -0.020596    0.945273
2005-2006  0.399671    608  0.023338    1.062013
2006-2007  0.372287    599 -0.004046    0.989248
2007-2008  0.379139    604  0.002806    1.007455
2008-2009  0.369775    622 -0.006558    0.982573
2009-2010  0.371941    613 -0.004392    0.988329
2010-2011  0.346032    630 -0.030302    0.919482
2011-2012  0.376254    598 -0.000079    0.999790
2012-2013  0.346470    609 -0.029864    0.920645
2013-2014  0.385124    605  0.008791    1.023359
2014-2015  0.395731    609  0.019397    1.051543
2015-2016  0.355330    591 -0.021003    0.944189
2016-2017  0.377451    612  0.001118    1.002970
2017-2018  0.365449    602 -0.010885    0.971077
2018-2019  0.423140    605  0.046807    1.124377
2019-2020  0.376026    609 -0.000307    0.999184
2020-2021  0.404290    606  0.027957    1.074288
2021-2022  0.396072    611  0.019739    1.052450
2022-2023  0.380165    605  0.003832    1.010182
2023-2024  0.391892     74  0.015559    1.041342

home

          mean  count      diff  risk_ratio
home
0     0.291912   6961 -0.084421    0.775674
1     0.459090   7101  0.082757    1.219903

## 2.5. Mutual information (Categorical variables)

In [23]:
def mutual_info_churn_score(series):
    return mutual_info_score(series, df_full_train.win)

In [24]:
mi = df_full_train[categorical_variables].apply(mutual_info_churn_score)
mi.sort_values(ascending=False)

team        0.034807
opponent    0.027517
home        0.014987
season      0.000718
dtype: float64

## 2.6 Correlation (Numerical variables)

In [31]:
numerical_corr = df_full_train[numerical_variables].corrwith(df_full_train.win).abs().reset_index()
numerical_corr.columns = ['features','corr']
numerical_corr.sort_values(by=['corr'], ascending=False)

                       features      corr
20             mooving_win_rate  0.485797
17              goal_difference  0.216905
18                     position  0.193018
19                     win_rate  0.173479
16                       points  0.126763
0              ftg_scored_total  0.122970
2              htg_scored_total  0.120665
21         mooving_goals_scored  0.116940
6            shots_target_total  0.083519
4                   shots_total  0.082223
10                corners_total  0.070055
1            ftg_received_total  0.065296
3            htg_received_total  0.059985
22       mooving_goals_received  0.058851
7   shots_target_received_total  0.055523
11        corners_against_total  0.051418
5          shots_received_total  0.048260
13  yellow_cards_opponent_total  0.042691
15     red_cards_opponent_total  0.037489
9          fouls_received_total  0.015241
14              red_cards_total  0.004268
12           yellow_cards_total  0.000638
8          fouls_commited_total  0.000460

In [36]:
numerical_corr.query(f"corr > {numerical_corr['corr'].mean()}")['features'].values

array(['ftg_scored_total', 'htg_scored_total', 'points',
       'goal_difference', 'position', 'win_rate', 'mooving_win_rate',
       'mooving_goals_scored'], dtype=object)

End of the notebook